import type { OperationalState } from "../entities";
import { withGuestGraphDefaults } from "../graph/memory";
import { DEFAULT_THREAD_FLAGS, SEED_UNIFIED_TIMELINE } from "./graph-seed";

const RAW_OPERATIONAL_STATE = {
  mounted: false,
  revenue: {
    revenueRecoveredToday: 4280,
    aiInfluencedRevenue: 12400,
    otaCommissionAvoided: 1860,
    upsellRevenueGenerated: 720,
    paymentRecoveryRevenue: 2180,
    humanTakeoverSavedRevenue: 1450,
    revenueAtRisk: 3120,
    recoverySuccessRate: 78,
    directBookingConversionValue: 5400,
    aiGeneratedRevenue: 8920,
    escalatedRevenueExposure: 1980,
    occupancyInfluencePct: 4.2,
  },
  aiImpact: {
    aiCloseRate: 34,
    aiAssistedRecoveryRate: 72,
    autonomousResolutionPct: 68,
    humanTakeoverSuccessPct: 91,
    escalationPreventionPct: 63,
    revenueInfluencedByAi: 12400,
    aiConfidenceStability: 87,
    guestRecoveryRate: 74,
    confidenceTrend: [82, 84, 83, 86, 85, 87, 87],
  },
  ota: {
    otaLeakagePct: 22,
    directConversionRate: 18,
    recoveredCommissionSavings: 1860,
    loyaltyConversions: 4,
    activeRecoveryWorkflows: 2,
  },
  activeRecoveries: [
    {
      id: "rj1",
      kind: "failed_payment",
      guestLabel: "Hans Mueller",
      roomLabel: "Triple Room · Jun 28–Jul 3",
      status: "active",
      bookingValueEur: 780,
      revenueSavedEur: 0,
      reservationId: "or2",
      conversationId: "c2",
      aiRationale:
        "Payment friction detected — AI issued alternate link + deposit split within policy.",
      steps: [
        {
          id: "s1",
          phase: "risk",
          title: "Payment risk detected",
          detail: "Card declined · €780 at risk",
          timestamp: "11:24",
          revenueDeltaEur: -780,
        },
        {
          id: "s2",
          phase: "ai_intervention",
          title: "AI recovery sequence",
          detail: "Alternate payment link + policy explanation",
          timestamp: "11:25",
        },
        {
          id: "s3",
          phase: "escalation",
          title: "Ops notified",
          detail: "Duty manager on standby · SLA 12m",
          timestamp: "11:26",
        },
      ],
    },
    {
      id: "rj2",
      kind: "ota_to_direct",
      guestLabel: "Sophie Martin",
      roomLabel: "Superior Double · Aug 2–6",
      status: "recovered",
      bookingValueEur: 1180,
      revenueSavedEur: 212,
      aiRationale: "OTA-origin guest offered direct rate match — commission avoided on close.",
      steps: [
        {
          id: "s1",
          phase: "risk",
          title: "OTA leakage flagged",
          detail: "Booking.com inquiry · 18% commission exposure",
          timestamp: "09:02",
          revenueDeltaEur: -212,
        },
        {
          id: "s2",
          phase: "ai_intervention",
          title: "Direct conversion workflow",
          detail: "Rate parity + loyalty perk surfaced",
          timestamp: "09:04",
        },
        {
          id: "s3",
          phase: "recovery",
          title: "Direct booking secured",
          detail: "Guest accepted secure payment link",
          timestamp: "09:18",
          revenueDeltaEur: 1180,
        },
        {
          id: "s4",
          phase: "confirmation",
          title: "Commission avoided",
          detail: "€212 OTA commission retained",
          timestamp: "09:19",
          revenueDeltaEur: 212,
        },
      ],
    },
    {
      id: "rj3",
      kind: "takeover_rescue",
      guestLabel: "Elena Petrov",
      roomLabel: "Deluxe Suite · Aug 12–15",
      status: "recovered",
      bookingValueEur: 2180,
      revenueSavedEur: 2180,
      aiRationale:
        "VIP policy edge — human takeover with AI context preserved prevented cancellation.",
      steps: [
        {
          id: "s1",
          phase: "risk",
          title: "Cancellation risk",
          detail: "Policy dispute · Russian thread · score 0.88",
          timestamp: "08:41",
          revenueDeltaEur: -2180,
        },
        {
          id: "s2",
          phase: "ai_intervention",
          title: "AI triage + escalation",
          detail: "Takeover recommended · context packet sent",
          timestamp: "08:42",
        },
        {
          id: "s3",
          phase: "escalation",
          title: "Human takeover",
          detail: "Maria L. joined · policy exception drafted",
          timestamp: "08:44",
        },
        {
          id: "s4",
          phase: "confirmation",
          title: "Booking rescued",
          detail: "VIP retained · €2,180 secured",
          timestamp: "08:52",
          revenueDeltaEur: 2180,
        },
      ],
    },
  ],
  revenueEvents: [
    {
      id: "st1",
      headline: "AI recovered €2,180 booking after payment friction",
      narrative: "VIP thread escalated with full context — human override closed within 8 minutes.",
      amountEur: 2180,
      attribution: "payment_recovery",
      timestamp: "08:52",
      conversationId: "c3",
      reservationId: "r-vip-1",
    },
    {
      id: "st2",
      headline: "Human escalation prevented VIP cancellation",
      narrative: "Policy edge case — AI recommended takeover; revenue exposure neutralized.",
      amountEur: 2180,
      attribution: "vip_intervention",
      timestamp: "08:52",
      conversationId: "c3",
    },
    {
      id: "st3",
      headline: "OTA recovery workflow saved 18% commission",
      narrative: "Direct conversion on Superior room — commission retained in-house.",
      amountEur: 212,
      attribution: "ota_commission",
      timestamp: "09:19",
      reservationId: "r-ota-1",
    },
    {
      id: "st4",
      headline: "AI upsell generated €120 additional ADR",
      narrative: "Late checkout + breakfast bundle accepted post-confirmation.",
      amountEur: 120,
      attribution: "ai_upsell",
      timestamp: "Yesterday",
      reservationId: "or1",
    },
  ],
  reservations: [
    {
      id: "or1",
      guest: "Sarah Johnson",
      initials: "SJ",
      room: "Deluxe Suite",
      checkIn: "Jun 15",
      checkOut: "Jun 20",
      guests: 2,
      nights: 5,
      currentStage: "confirmation",
      bookingValueEur: 850,
      revenueAtRiskEur: 0,
      channel: "Direct · WhatsApp",
      conversationId: "c4",
      attributions: [
        {
          kind: "direct_conversion",
          label: "Direct close",
          amountEur: 850,
          aiContributed: true,
          detail: "AI qualified + quoted",
        },
      ],
      timeline: [
        { stage: "inquiry", label: "Inquiry received", timestamp: "09:12", actor: "guest" },
        {
          stage: "quote",
          label: "Quote issued",
          timestamp: "09:18",
          financialImpactEur: 850,
          actor: "ai",
        },
        { stage: "payment_pending", label: "Payment link sent", timestamp: "09:22", actor: "ai" },
        {
          stage: "confirmation",
          label: "Confirmed",
          timestamp: "09:41",
          financialImpactEur: 850,
          actor: "system",
        },
        {
          stage: "upsell",
          label: "Upsell accepted",
          timestamp: "10:02",
          financialImpactEur: 95,
          actor: "ai",
          note: "ADR +€95",
        },
      ],
    },
    {
      id: "or2",
      guest: "Hans Mueller",
      initials: "HM",
      room: "Triple Room",
      checkIn: "Jun 28",
      checkOut: "Jul 3",
      guests: 3,
      nights: 5,
      currentStage: "payment_risk",
      bookingValueEur: 780,
      revenueAtRiskEur: 780,
      channel: "Direct · WhatsApp",
      conversationId: "c2",
      attributions: [
        {
          kind: "payment_recovery",
          label: "Recovery in progress",
          amountEur: 780,
          aiContributed: true,
          detail: "Alternate link issued",
        },
      ],
      timeline: [
        { stage: "inquiry", label: "Inquiry", timestamp: "10:45", actor: "guest" },
        { stage: "quote", label: "Offer sent", timestamp: "11:02", financialImpactEur: 780, actor: "ai" },
        { stage: "payment_pending", label: "Payment pending", timestamp: "11:10", actor: "ai" },
        {
          stage: "payment_risk",
          label: "Payment failed",
          timestamp: "11:24",
          financialImpactEur: -780,
          actor: "system",
        },
        { stage: "recovery", label: "AI recovery active", timestamp: "11:25", actor: "ai" },
      ],
    },
    {
      id: "or3",
      guest: "Mohammed Al-Said",
      initials: "MS",
      room: "Family Room",
      checkIn: "Jul 1",
      checkOut: "Jul 7",
      guests: 4,
      nights: 6,
      currentStage: "retention",
      bookingValueEur: 1200,
      revenueAtRiskEur: 0,
      channel: "Direct · Web",
      attributions: [
        { kind: "direct_conversion", label: "Direct booking", amountEur: 1200, aiContributed: true },
        {
          kind: "ota_commission",
          label: "OTA avoided (est.)",
          amountEur: 216,
          aiContributed: true,
          detail: "18% commission",
        },
      ],
      timeline: [
        { stage: "inquiry", label: "Web inquiry", timestamp: "Yesterday", actor: "guest" },
        {
          stage: "confirmation",
          label: "Confirmed",
          timestamp: "Yesterday",
          financialImpactEur: 1200,
          actor: "ai",
        },
        { stage: "retention", label: "Pre-arrival nurture", timestamp: "Today", actor: "ai" },
      ],
    },
    {
      id: "or4",
      guest: "Giulia Romano",
      initials: "GR",
      room: "Double Room",
      checkIn: "Jul 10",
      checkOut: "Jul 15",
      guests: 2,
      nights: 5,
      currentStage: "confirmation",
      bookingValueEur: 650,
      revenueAtRiskEur: 0,
      channel: "Instagram → Direct",
      attributions: [
        {
          kind: "abandoned_recovery",
          label: "Abandoned booking saved",
          amountEur: 650,
          aiContributed: true,
        },
      ],
      timeline: [
        { stage: "quote", label: "Quote idle", timestamp: "10:08", actor: "guest" },
        { stage: "recovery", label: "AI re-engagement", timestamp: "10:55", actor: "ai" },
        {
          stage: "confirmation",
          label: "Recovered",
          timestamp: "11:14",
          financialImpactEur: 650,
          actor: "system",
        },
      ],
    },
  ],
  guests: [
    {
      id: "g1",
      name: "Elena Petrov",
      initials: "EP",
      avatarColor: "bg-rose-600",
      segment: "vip",
      lifetimeValueEur: 4200,
      aiInfluencedRevenueEur: 2180,
      recoveryCount: 1,
      vipRescueCount: 1,
      otaConversionCount: 0,
      lastAttribution: {
        kind: "vip_intervention",
        label: "VIP rescue",
        amountEur: 2180,
        aiContributed: true,
      },
      conversationId: "c3",
    },
    {
      id: "g2",
      name: "Hans Mueller",
      initials: "HM",
      avatarColor: "bg-blue-600",
      segment: "standard",
      lifetimeValueEur: 1560,
      aiInfluencedRevenueEur: 780,
      recoveryCount: 0,
      vipRescueCount: 0,
      otaConversionCount: 0,
      lastAttribution: {
        kind: "payment_recovery",
        label: "Payment recovery",
        amountEur: 780,
        aiContributed: true,
      },
      conversationId: "c2",
    },
    {
      id: "g3",
      name: "Sophie Martin",
      initials: "SM",
      avatarColor: "bg-violet-600",
      segment: "ota_origin",
      lifetimeValueEur: 2400,
      aiInfluencedRevenueEur: 1180,
      recoveryCount: 1,
      vipRescueCount: 0,
      otaConversionCount: 1,
      lastAttribution: {
        kind: "ota_commission",
        label: "OTA → direct",
        amountEur: 212,
        aiContributed: true,
      },
      conversationId: "c-ota",
    },
    {
      id: "g4",
      name: "Sarah Johnson",
      initials: "SJ",
      avatarColor: "bg-emerald-600",
      segment: "standard",
      lifetimeValueEur: 2890,
      aiInfluencedRevenueEur: 945,
      recoveryCount: 0,
      vipRescueCount: 0,
      otaConversionCount: 0,
      lastAttribution: { kind: "ai_upsell", label: "ADR uplift", amountEur: 95, aiContributed: true },
      conversationId: "c4",
    },
  ],
  threads: [
    {
      id: "c1",
      guestName: "Ahmet Yılmaz",
      initials: "AY",
      avatarColor: "bg-violet-600",
      channel: "WhatsApp",
      language: "TR",
      status: "ai_active",
      lastMessage: "15-20 Temmuz arası çift kişilik odanız müsait mi?",
      time: "2m ago",
      unread: 2,
      revenueExposureEur: 0,
      attributions: [],
      flags: {
        ...DEFAULT_THREAD_FLAGS,
      },
    },
    {
      id: "c2",
      guestName: "Hans Mueller",
      initials: "HM",
      avatarColor: "bg-blue-600",
      channel: "WhatsApp",
      language: "DE",
      status: "ai_active",
      lastMessage: "I already tried the payment link twice. It keeps failing.",
      time: "6m ago",
      unread: 0,
      revenueExposureEur: 780,
      reservationId: "or2",
      guestId: "g2",
      attributions: [
        {
          kind: "payment_recovery",
          label: "Payment recovery saved €780 booking",
          amountEur: 780,
          aiContributed: true,
        },
      ],
      flags: {
        ...DEFAULT_THREAD_FLAGS,
        paymentRisk: true,
        recoveryActive: true,
        memoryAttached: true,
        priorRiskDetected: true,
      },
    },
    {
      id: "c3",
      guestName: "Elena Petrov",
      initials: "EP",
      avatarColor: "bg-rose-600",
      channel: "Instagram",
      language: "RU",
      status: "human_takeover",
      lastMessage: "Policy exception approved — booking secured",
      time: "12m ago",
      unread: 0,
      revenueExposureEur: 0,
      guestId: "g1",
      attributions: [
        {
          kind: "vip_intervention",
          label: "VIP intervention prevented cancellation risk",
          amountEur: 2180,
          aiContributed: true,
        },
        {
          kind: "takeover_rescue",
          label: "Human takeover rescued booking",
          amountEur: 2180,
          aiContributed: false,
        },
      ],
      flags: {
        ...DEFAULT_THREAD_FLAGS,
        humanTakeover: true,
        vipEscalation: true,
        memoryAttached: true,
        vipHistory: true,
        priorRiskDetected: true,
      },
    },
    {
      id: "c4",
      guestName: "Sarah Johnson",
      initials: "SJ",
      avatarColor: "bg-emerald-600",
      channel: "Web",
      language: "EN",
      status: "resolved",
      lastMessage: "Upsell bundle confirmed — late checkout added",
      time: "1h ago",
      unread: 0,
      revenueExposureEur: 0,
      reservationId: "or1",
      guestId: "g4",
      attributions: [
        {
          kind: "ai_upsell",
          label: "AI upsell increased ADR by €95",
          amountEur: 95,
          aiContributed: true,
        },
      ],
      flags: {
        ...DEFAULT_THREAD_FLAGS,
        memoryAttached: true,
        directBookingCandidate: true,
      },
    },
  ],
  alerts: [
    {
      id: "al1",
      title: "Ödeme sorunu tespit edildi",
      detail: "Hans Mueller · €780 · kurtarma devam ediyor",
      severity: "warning",
      timestamp: "6m ago",
      read: false,
      financialEur: 780,
      reservationId: "or2",
      guestLabel: "Hans Mueller",
      reason: "Ödeme sorunu — kurtarma başlatıldı",
      orchestrationStatus: "recovery_active",
      aiConfidence: 84,
      escalationLevel: "urgent",
      affectedSystems: ["revenue", "reservation", "recovery", "alert", "memory"],
    },
    {
      id: "al2",
      title: "VIP misafir — ekip devraldı",
      detail: "Elena Petrov · insan desteği tamamlandı · €2.180 güvence altında",
      severity: "success",
      timestamp: "12m ago",
      read: true,
      financialEur: 2180,
      guestLabel: "Elena Petrov",
    },
    {
      id: "al3",
      title: "OTA → direkt fırsat",
      detail: "Sophie Martin · direkt fiyat eşleştirmesi sürüyor",
      severity: "info",
      timestamp: "1h ago",
      read: true,
      guestLabel: "Sophie Martin",
    },
  ],
  aiActions: [
    {
      id: "ai1",
      action: "Payment recovery sequence initiated",
      rationale: "Card decline on €780 — alternate link + split deposit within policy bounds.",
      timestamp: "11:25",
      financialImpactEur: 780,
      reservationId: "or2",
      conversationId: "c2",
    },
    {
      id: "ai2",
      action: "Human takeover recommended",
      rationale: "VIP policy edge · cancellation likelihood 0.88 · context packet prepared.",
      timestamp: "08:42",
      financialImpactEur: 2180,
      conversationId: "c3",
    },
  ],
  auditEvents: [
    {
      id: "a1",
      action: "Payment recovery sequence initiated",
      actor: "ai",
      rationale: "Card decline on €780 — alternate link + split deposit within policy bounds.",
      timestamp: "11:25",
      financialImpactEur: 780,
      attribution: "payment_recovery",
      reservationId: "or2",
    },
    {
      id: "a2",
      action: "Human takeover recommended",
      actor: "ai",
      rationale: "VIP policy edge · cancellation likelihood 0.88 · context packet prepared.",
      timestamp: "08:42",
      financialImpactEur: 2180,
      attribution: "vip_intervention",
    },
    {
      id: "a3",
      action: "OTA → direct conversion workflow",
      actor: "ai",
      rationale: "Rate parity offer — 18% commission avoidance on close.",
      timestamp: "09:04",
      financialImpactEur: 212,
      attribution: "ota_commission",
    },
    {
      id: "a4",
      action: "Booking confirmed post-recovery",
      actor: "human",
      rationale: "Maria L. closed VIP exception — AI context preserved in thread.",
      timestamp: "08:52",
      financialImpactEur: 2180,
      attribution: "takeover_rescue",
    },
    {
      id: "a5",
      action: "Upsell bundle accepted",
      actor: "ai",
      rationale: "Post-confirmation ADR uplift — late checkout + breakfast.",
      timestamp: "10:02",
      financialImpactEur: 95,
      attribution: "ai_upsell",
      reservationId: "or1",
    },
  ],
  operationsFeed: [
    {
      id: "f1",
      title: "Ödeme sorunu · kurtarma aktif",
      meta: "Hans Mueller · €780 · alternatif ödeme bağlantısı gönderildi",
      time: "6m ago",
      tone: "border-l-amber-400/70 bg-amber-500/[0.04]",
      financialEur: 780,
      eventType: "PAYMENT_FAILED",
    },
    {
      id: "f2",
      title: "VIP rezervasyon kurtarıldı",
      meta: "Elena Petrov · ekip devraldı · €2.180 güvence altında",
      time: "12m ago",
      tone: "border-l-emerald-400/65 bg-emerald-500/[0.04]",
      financialEur: 2180,
      eventType: "HUMAN_TAKEOVER",
    },
    {
      id: "f3",
      title: "OTA komisyonu tasarruf edildi",
      meta: "Sophie Martin · direkt rezervasyon · €212 tasarruf",
      time: "1h ago",
      tone: "border-l-violet-400/70 bg-violet-500/[0.04]",
      financialEur: 212,
      eventType: "OTA_CONVERSION",
    },
    {
      id: "f4",
      title: "Ek satış · ADR artışı",
      meta: "Sarah Johnson · onay sonrası +€95",
      time: "1h ago",
      tone: "border-l-blue-400/70 bg-blue-500/[0.04]",
      financialEur: 95,
      eventType: "UPSELL_ACCEPTED",
    },
  ],
  unifiedTimeline: SEED_UNIFIED_TIMELINE,
  lastPropagation: null,
  mutationPulseAt: null,
  lastEventAt: null,
};

export const INITIAL_OPERATIONAL_STATE: OperationalState = {
  ...(RAW_OPERATIONAL_STATE as OperationalState),
  guests: RAW_OPERATIONAL_STATE.guests.map((g) =>
    withGuestGraphDefaults(g as Parameters<typeof withGuestGraphDefaults>[0])
  ),
};
